application : dubtracktechnicaltest
version : 1
runtime : python27
api_version : 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: ssl
  version: latest

handlers:
- url: .*
  script: app.app
